### ISSUE TITLE
trouble loading the streamlit_autorefresh.st_autorefresh component

### ISSUE THREAD

**Issue by vgattani-ds** [kmcgrady/streamlit-autorefresh#1]
Hi Team,

I am using streamlit_autorefresh in the streamlit to auto-refresh the dashboard. The code is deployed in AWS EC2. The app is running fine, but the auto-refresh utility is not working. The displayed error is below:
'''
Your app is having trouble loading the streamlit_autorefresh.st_autorefresh component.

(The app is attempting to load the component from **, and hasn't received its "streamlit:componentReady"** message.)

If this is a development build, have you started the dev server?
If this is a release build, have you compiled the frontend?
For more troubleshooting help, please see the Streamlit Component docs or visit our forums.
'''

Streamlit Version: 0.88.0
Python Version: 3.8.5

**Comment by kmcgrady** [comment]
Hey @vgattani-ds and @DLee-AU Thanks for filing the issue (I for some reason do not get notifications on this). Do you by chance have an example URL for this? The fact that it's working locally and on Streamlit Cloud suggests that there's something especially weird going on in Streamlit on AWS.
