### ISSUE TITLE
autorefresh SOME things

### ISSUE THREAD

**Issue by malfonsoNeoris** [kmcgrady/streamlit-autorefresh#2]
hi, this is great.
can i autorefresh only part of the application?
for example im loading some ML models, and capturing a video and doing thins on the video.
this refresh is great for that.. but i only want to rerun a funcion.. not the whole script.
thanks

**Comment by kmcgrady** [comment]
Hey @malfonsoNeoris ! At this time, Streamlit does not allow refreshing a specific function without rerunning a script. The only option would be to consider [caching](https://docs.streamlit.io/library/advanced-features/caching) so when the script is rerun, heavy work is not executed multiple times. We have [some new experimental caching primitives](https://blog.streamlit.io/new-experimental-primitives-for-caching/) that might also help.
